[build]
  publish = "build" # Assuming your React build output is in the 'build' folder
  functions = "netlify/functions" # This is where your serverless functions will live

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/api/:splat"
  status = 200